kind: pipeline
name: default

steps:
- name: tests
  image: tryffel/golang-alsa:13.7
  volumes:
  - name: deps
    path: /go
  commands:
  - go mod download
  - go test ./...
    #- go build

trigger:
  event:
    include:
    - push
    - pull_request

volumes:
- name: deps
  temp: {}

