# Jellycli reference configuration file

# Jellycli does not (yet) parse yaml comments.
# Do not copy this file, let Jellycli create / initialize
# the config file.
# Any key can be overridden with environment variables,

# Jellyfin settings
jellyfin:
  url: http://localhost/jellyfin
  # To force logout, clear token
  token:
  # Don't touch these
  user_id:
  device_id:
  server_id:
  music_view:

# Subsonic configuration
# Salt & token is created automatically from password.
# To force logout, remote salt & token
subsonic:
  url: http://localhost
  username:
  salt:
  token:
# Player & Gui settings
player:
  # Server to connect to by default. Either jellyfin or subsonic..
  server: jellyfin
  # Paging, default: 100
  page_size: 100
  # Logging
  log_file: /tmp/jellycli.log
  # Allowed values: trace|debug|info|warning|error|fatal
  log_level: warning

  # debug mode. When enabled, a new shortcut is added for creating debug dump.
  debug_mode: false

  # Limit recent songs to a sensible value.
  # When set to false, 'recent songs' are actually
  # all songs ever listened on this account
  limit_recent_songs: true

  # Enable mouse support
  enable_mouse: true

  # If mouse support is enabled, maximum interval (ms) for double click.
  # Default: 200
  mouse_double_click_interval_ms: 200

  # Low-level audio buffer duration. Set smaller (e.g. 50ms) for less delay and more cpu usage,
  # increase if audio stutters (to 300, or even 500) or to use less cpu. Default value: 150.
  audio_buffering_ms: 150

  # http buffering duration in seconds, how much to buffer from server before starting audio
  http_buffering_s: 5

  # max http buffering limit in MiB. Setting this to high enough ensures smooth play even with longer tracks.
  # 20 MiB with flac ~ 10 min of audio buffered.
  http_buffering_limit_mem: 20

  # If enabled, user can control playback remotely with another client.
  enable_remote_control: true

  # Configure which fields get searched. Values are case-sensitive.
  search_types:
    - Artist
    - Album
    - Song
    - Playlist
