# Jellycli reference configuration file

# This file is for reference purposes only. Jellycli creates file pointed to it as config file
# if the file does not exist or is empty.
# Any key can be set with environment variables. See Readme or use command
# jellycli list-env to list available variables.

# Jellyfin settings. All values are saved when logging in.
jellyfin:
  url: http://localhost/jellyfin
  # To force logout, clear token
  token:
  # Don't touch these
  user_id:
  device_id:
  server_id:
  music_view:

# Audio & application settings
player:
  # Server to connect to by default. Either jellyfin or subsonic.
  server: jellyfin

  # Logging
  log_file: /tmp/jellycli.log

  # Allowed values: trace|debug|info|warning|error|fatal
  log_level: warning

  # Low-level audio buffer duration. Set smaller (e.g. 50ms) for less delay and more cpu usage,
  # increase if audio stutters (to 300, or even 500) or to use less cpu. Default value: 150.
  audio_buffering_ms: 150

  # http buffering duration in seconds, how much to buffer from server before starting audio
  http_buffering_s: 5

  # max http buffering limit in MiB. Setting this to high enough ensures smooth play even with longer tracks.
  # 20 MiB with flac ~ 10 min of audio buffered.
  http_buffering_limit_mem: 20

  # If enabled, user can control playback remotely with another client.
  enable_remote_control: true


  # If enabled, playback reporting (start, progress, stop) is disabled.
  disable_playback_reporting: false
